name: CI

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/**'
      - 'Cargo**'
      - 'src/**/*.rs'
      - 'tests/**/*.rs'

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: jluszcz/github-utils/.github/workflows/rust-ci.yml@v2
